trigger:
  - main

pool:
  name: 'Default'  # Use 'ubuntu-latest' if you are not using a self-hosted agent

variables:
 
  - group: aws_ecr_repo  # Ensure this variable group exists in your pipeline library
  - name: IMAGE_TAG
    value: $(Build.BuildId)

stages:
  - stage: DockerLogin
    displayName: Docker Login
    jobs:
      - job: DockerLogin
        displayName: Docker Login Job
        steps:
          - script: |
              echo "Logging into AWS ECR..."
              aws ecr get-login-password --region "$(Region)" | \
              docker login --username AWS --password-stdin "$(aws_account)".dkr.ecr."$(Region)".amazonaws.com
            displayName: 'Login to Docker'

  - stage: BuildPush
    displayName: Build and Push Docker Image
    dependsOn: DockerLogin
    jobs:
      - job: DockerBuildPush
        displayName: Build and Push Image
        steps: 
          - checkout: self

          - script: |
              echo "IMAGE_NAME: $(IMAGE_NAME)"
              echo "IMAGE_TAG: $(IMAGE_TAG)"
            displayName: 'Print Docker Variables'

          - script: |
              echo "Building the Docker webserver image"
              docker build -t $(IMAGE_NAME_WEBSERVER):$(IMAGE_TAG) -f project/docker/app/Dockerfile .

              echo "Building the Docker nginx image"
              docker build -t $(IMAGE_NAME_NGINX):$(IMAGE_TAG) -f project/docker/nginx/Dockerfile .

              echo "Pushing the Docker images..."
              docker push $(IMAGE_NAME_WEBSERVER):$(IMAGE_TAG)
              docker push $(IMAGE_NAME_NGINX):$(IMAGE_TAG)
            displayName: 'Build and Push Docker Images'

  - stage: Terraform
    displayName: Terraform Apply
    dependsOn: BuildPush
    variables:
      CONTAINER_IMAGE_WEBSERVER: "$(IMAGE_NAME_WEBSERVER):$(IMAGE_TAG)"  
      CONTAINER_IMAGE_NGINX: "$(IMAGE_NAME_NGINX):$(IMAGE_TAG)"  

    jobs:
      - job: Terraform
        displayName: Terraform Job
        steps:
          - checkout: self

          - script: terraform version
            displayName: 'Check Terraform Version'

          - script: terraform init
            displayName: 'Terraform Init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure'
            

          - script: |
              terraform plan \
                -var="container_image_webserver=$(CONTAINER_IMAGE_WEBSERVER)" \
                -var="container_image_nginx=$(CONTAINER_IMAGE_NGINX)"
            displayName: 'Terraform Plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure'
           

          - script: |
              terraform apply -auto-approve \
                -var="container_image_webserver=$(CONTAINER_IMAGE_WEBSERVER)" \
                -var="container_image_nginx=$(CONTAINER_IMAGE_NGINX)"
            displayName: 'Terraform Apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure'
           
